Config = {}



Config.tequila = {
    label = "Tequila Shop",
        slots = 20,
        items = {
            [1] = {
                name = "vodka",
                price = 175,
                amount = 5,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "burger-mshake",
                price = 20,
                amount = 5,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "beer",
                price = 25,
                amount = 5,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "kurkakola",
                price = 7,
                amount = 5,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "ecolalight",
                price = 7,
                amount = 5,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "pisswasser",
                price = 50,
                amount = 5,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "logger",
                price = 50,
                amount = 5,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "dusche",
                price = 150,
                amount = 5,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "ambeer",
                price = 50,
                amount = 5,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "amarone",
                price = 60,
                amount = 5,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "dolceto",
                price = 60,
                amount = 6,
                info = {},
                type = "item",
                slot = 11,
            },
            [12] = {
                name = "pisswasser2",
                price = 65,
                amount = 1,
                info = {},
                type = "item",
                slot = 12,
            },
            [13] = {
                name = "pisswasser3",
                price = 65,
                amount = 5,
                info = {},
                type = "item",
                slot = 13,
            },
            [14] = {
                name = "bellini",
                price = 45,
                amount = 5,
                info = {},
                type = "item",
                slot = 14,
            },
            [15] = {
                name = "strawmargarita",
                price = 45,
                amount = 5,
                info = {},
                type = "item",
                slot = 15,
            },
            [16] = {
                name = "margarita",
                price = 45,
                amount = 15,
                info = {},
                type = "item",
                slot = 16,
            },
            [17] = {
                name = "pinacolada",
                price = 45,
                amount = 5,
                info = {},
                type = "item",
                slot = 17,
            },
            [18] = {
                name = "screwdriver",
                price = 40,
                amount = 5,
                info = {},
                type = "item",
                slot = 18,
            },
            [19] = {
                name = "longisland",
                price = 50,
                amount = 5,
                info = {},
                type = "item",
                slot = 19,
            },
            [20] = {
                name = "cosmopolitan",
                price = 55,
                amount = 5,
                info = {},
                type = "item",
                slot = 20,
            },
        }
    }


Config.Products = {
    ["normal"] = {
        [1] = {
            name = "bandage",
            price = 40,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "rolling_paper",
            price = 3,
            amount = 5000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cigar",
            price = 40,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        -- [5] = {
        --     name = "lighter",
        --     price = 15,
        --     amount = 100,
        --     info = {},
        --     type = "item",
        --     slot = 5,
        -- },
        [4] = {
            name = "sandwich",
            price = 33,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "water_bottle",
            price = 33,
            amount = 10,
            info = {},
            type = "item",
            slot = 5,
        },
        -- [7] = {
        --     name = "redwoodcigs",
        --     price = 22,
        --     amount = 100,
        --     info = {},
        --     type = "item",
        --     slot = 7,
        -- },
        -- [8] = {
        --     name = "cardiaquecigs",
        --     price = 20,
        --     amount = 100,
        --     info = {},
        --     type = "item",
        --     slot = 8,
        -- },
        -- [9] = {
        --     name = "yukoncigs",
        --     price = 21,
        --     amount = 100,
        --     info = {},
        --     type = "item",
        --     slot = 9,
        -- },
        [6] = {
            name = "kq_outfitbag",
            price = 100,
            amount = 20,
            info = {},
            type = "item",
            slot = 6,
        },
    },
    ["casino1"] = {
        [1] = {
            name = "vodka",
            price = 175,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "burger-mshake",
            price = 20,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "beer",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "kurkakola",
            price = 7,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "ecolalight",
            price = 7,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "pisswasser",
            price = 50,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "logger",
            price = 50,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "dusche",
            price = 150,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "ambeer",
            price = 50,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "amarone",
            price = 60,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "dolceto",
            price = 60,
            amount = 6,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "pisswasser2",
            price = 65,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "pisswasser3",
            price = 65,
            amount = 5,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "bellini",
            price = 45,
            amount = 5,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "strawmargarita",
            price = 45,
            amount = 5,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "margarita",
            price = 45,
            amount = 15,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "pinacolada",
            price = 45,
            amount = 5,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "screwdriver",
            price = 40,
            amount = 5,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "longisland",
            price = 50,
            amount = 5,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "cosmopolitan",
            price = 55,
            amount = 5,
            info = {},
            type = "item",
            slot = 20,
        },
    },
    ["repairkitbennys"] = {
        [1] = {
            name = "repairkit",
            price = 400,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        -- [2] = {
        --     name = "bathroomkey",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 2,
        -- },
        -- [3] = {
        --     name = "casino_member",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 3,
        -- },
    },
    ["repairkitbennys2"] = {
        [1] = {
            name = "repairkit",
            price = 400,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        -- [2] = {
        --     name = "bathroomkey",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 2,
        -- },
        -- [3] = {
        --     name = "casino_member",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 3,
        -- },
    },
    ["casino2"] = {
        [1] = {
            name = "casinochips",
            price = 0,
            amount = 10000000,
            info = {},
            type = "item",
            slot = 1,
        },
        -- [2] = {
        --     name = "bathroomkey",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 2,
        -- },
        -- [3] = {
        --     name = "casino_member",
        --     price = 0,
        --     amount = 1,
        --     info = {},
        --     type = "item",
        --     slot = 3,
        -- },
    },
    ["yellowjack"] = {
        [1] = {
            name = "yellowvodka",
            price = 0,
            amount = 1000000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "beer",
            price = 0,
            amount = 1000000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "burger-fries",
            price = 0,
            amount = 1000000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "ecola",
            price = 0,
            amount = 1000000,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["digitalden"] = {
        [1] = {
            name = "classic_phone",
            price = 1275,
            amount = 3,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    -- ["petstore"] = {
    --     [1] = {
    --         name = "pethealth",
    --         price = 295,
    --         amount = 3,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [2] = {
    --         name = "petfood",
    --         price = 315,
    --         amount = 3,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [3] = {
    --         name = "petthirst",
    --         price = 265,
    --         amount = 3,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [4] = {
    --         name = "petrope",
    --         price = 465,
    --         amount = 3,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [5] = {
    --         name = "petball",
    --         price = 455,
    --         amount = 3,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    -- },
    ["beekeeping"] = {
        [1] = {
            name = "beehive",
            price = 560,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "beequeen",
            price = 415,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    ["taco"] = {
        [1] = {
            name = "tortillas",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "ground-beef",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cheddar-cheese",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "butter",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "chicken",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },       
		[6] = {
            name = "lettuce",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
		[7] = {
            name = "tortilla-chips",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
		[8] = {
            name = "carbonated-water",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
		[9] = {
            name = "sugar-cubes",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "taco-tomato",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "gelato",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
    },
    ["darkcivthings"] = {
        [1] = {
            name = "electronickit",
            price = 1450,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "big_drill",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "drill",
            price = 2000,
            amount = 1,
            info = {},
            type = "item",
            slot =3,
        },
        [4] = {
            name = "thermite",
            price = 2250,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "tracker",
            price = 65000,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "encryptedtablet",
            price = 35000,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "thermite_bomb",
            price = 3000,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "c4_bomb",
            price = 3350,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "bag",
            price = 3750,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "cutter",
            price = 1100,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "fakeplate",
            price = 7500,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "screwdriverset",
            price = 5000,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "uconnectair",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "laptop2",
            price = 5500,
            amount = 1,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "dealers_laptop",
            price = 5500,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
        },
    },
    ["CUSTOMCAFEDRINKS"] = {
        [1] = {
            name = "coffee",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["CUSTOMCAFE"] = {
        [1] = {
            name = "cocabeans",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whipcream",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "chocolate",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "sprinkles",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "milkbottle",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "teabag",
            price = 0,
            amount = 1000,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "carbonated-water",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
		[8] = {
            name = "sugar-cubes",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
    },
    ["police"] = {
        [1] = {
            name = "sandwich",
            price = 8,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 7,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "quinoa",
            price = 7,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["mechanictools2"] = {
        [1] = {
            name = "underglow_controller",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "harness",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "nos",
            price = 25000,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "noscolour",
            price = 5000,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "vpn_racing",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "dongle",
            price = 350,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
    },
    ["mechanictools"] = {
        [1] = {
            name = "underglow_controller",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "harness",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "firework1",
            price =300,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "firework2",
            price = 300,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "firework3",
            price = 300,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "firework4",
            price = 300,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "binoculars",
            price = 400,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "diving_gear",
            price = 3000,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "box",
            price = 100,
            amount = 3,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "parachute",
            price = 1200,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "backpack1",
            price = 3500,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "briefcase",
            price = 1200,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "repairkit",
            price = 350,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "advancedlockpick",
            price = 350,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "lockpick",
            price = 300,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "screwdriverset",
            price = 1050,
            amount = 1,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "head_bag",
            price = 200,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "briefcaselockpicker",
            price = 1350,
            amount = 1,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "nightvision",
            price = 3100,
            amount = 1,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "metaldetector",
            price = 4000,
            amount = 1,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "notepad",
            price = 250,
            amount = 1,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "tablet",
            price = 550,
            amount = 1,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "notebook",
            price = 450,
            amount = 1,
            info = {},
            type = "item",
            slot = 21,
        },
    },
    ["coffeeshop"] = {
        [1] = {
            name = "empty_plastic_bag",
            price = 5,
            amount = 150,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "rolling_paper",
            price = 5,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "fishingrod",
            price = 700,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [4] = {
            name = "fishbait",
            price = 20,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
    },
    ["leisureshop"] = {
        [1] = {
            name = "parachute",
            price = 5000,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 175,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },    
        [3] = {
            name = "diving_gear",
            price = 350,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        -- [4] = {
        --     name = "smoketrailred",
        --     price = 250,
        --     amount = 50,
        --     info = {},
        --     type = "item",
        --     slot = 4,
        -- },
    },
    ["electricshop"] = {
        [1] = {
            name = "classic_phone",
            price = 700,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "shitgpu",
            price = 1950,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },    
        [3] = {
            name = "1050gpu",
            price = 3150,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "1060gpu",
            price = 4400,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "1080gpu",
            price = 5650,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "2080gpu",
            price = 7750,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "3060gpu",
            price = 10250,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "4090gpu",
            price = 19050,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "thermalpast",
            price = 1250,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "radio",
            price = 3000,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "transponder",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "hacking_device",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "decrypter",
            price = 850,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
    },
    ["pokemon"] = {
        [1] = {
            name = 'boosterpack',
            price = 400,
            amount = 50,
            info = {},
            type = 'item',
            slot = 1,
        },
        [2] = {
            name = 'boosterbox',
            price = 1600,
            amount = 10,
            info = {},
            type = 'item',
            slot = 2,
        },
        [3] = {
            name = 'pokebox',
            price = 250,
            amount = 50,
            info = {},
            type = 'item',
            slot = 3,
        }
    },
    -- ["blackmarketvpn"] = {
    --     [1] = {
    --         name = "vpn_blackmarket",
    --         price = 150000,
    --         amount = 1,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    -- },
    -- ["attch"] = {
    --     [1] = {
    --         name = "uzi_extendedclip",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [2] = {
    --         name = "weapon_uzi_woodstock",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 2,
    --     },
    --     [3] = {
    --         name = "smg_suppressor",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 3,
    --     },
    --     [4] = {
    --         name = "weapon_uzi_foldstock",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 4,
    --     },
    --     [5] = {
    --         name = "mac10_extendedclip",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 5,
    --     },
    --     [6] = {
    --         name = "advancedrifle_extendedclip",
    --         price = 10000,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 6,
    --     },
    --     [7] = {
    --         name = "rifle_suppressor",
    --         price = 10000,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 7,
    --     },
    --     [8] = {
    --         name = "heavypistol_extendedclip",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 8,
    --     },
    --     [9] = {
    --         name = "pistol_suppressor",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 9,
    --     },
    --     [10] = {
    --         name = "snspistol_extendedclip",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 1,
    --     },
    --     [11] = {
    --         name = "pistol_extendedclip",
    --         price = 7500,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 11,
    --     },
    --     [12] = {
    --         name = "bullpuprifle_extendedclip",
    --         price = 10000,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 12,
    --     },
    --     [13] = {
    --         name = "assaultsmg_extendedclip",
    --         price = 10000,
    --         amount = 5,
    --         info = {},
    --         type = "item",
    --         slot = 13,
    --     },
    -- },
    ["pawnshop"] = {
        [1] = {
            name = "laptop2",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "dongle",
            price = 350,
            amount = 1,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "thermite",
            price = 550,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "advancedlockpick",
            price = 750,
            amount = 1,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "lockpick",
            price = 650,
            amount = 1,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "decrypter",
            price = 850,
            amount = 1,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "screwdriverset",
            price = 1050,
            amount = 1,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "head_bag",
            price = 200,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "briefcaselockpicker",
            price = 1350,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "cctv",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "360cctv",
            price = 1500,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "camviewer",
            price = 1000,
            amount = 1,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "harness",
            price = 1350,
            amount = 1,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "transponder",
            price = 350,
            amount = 1,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "electronickit",
            price = 250,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "big_drill",
            price = 2500,
            amount = 1,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "drill",
            price = 2000,
            amount = 1,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "hacking_device",
            price = 700,
            amount = 1,
            info = {},
            type = "item",
            slot = 18,
        },
    },
    ["weapons"] = {
        [1] = {
            name = "weapon_bats",
            price = 2000,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [2] = {
            name = "weapon_crowbar",
            price = 3350,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [3] = {
            name = "weapon_hammer",
            price = 1750,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [4] = {
            name = "weapon_poolcue",
            price = 1750,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [5] = {
            name = "pistol_ammo",
            price = 200,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [6] = {
            name = "rifle_ammo",
            price = 300,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [7] = {
            name = "smg_ammo",
            price = 250,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [8] = {
            name = "heavyarmor",
            price = 300,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
    },
    ["phermacy"] = {
        [1] = {
            name = "bandage",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "walkstick",
            price = 350,
            amount = 20,
            info = {},
            type = "item",
            slot = 2,
        },
    },
}

Config.Locations = {
    ["phermacy"] = {
        ["label"] = "Pillbox Phermacy",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(310.75662, -585.329, 43.26757),
            --[2] =vector3(1830.77, 3676.5, 34.27)
        },
        ["products"] = Config.Products["phermacy"],
        ["showblip"] = false,
    },
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-48.44, -1757.86, 29.42),
            [2] = vector3(-47.23, -1756.58, 29.42)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(25.7, -1347.3, 29.49),
            [2] = vector3(25.7, -1344.99, 29.49)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["laptop"] = {
        ["label"] = "Buy Laptop",
        ["type"] = "laptop",
        ["coords"] = {
            [1] = vector3(-1437.114, -373.686, 38.18143)
        },
        ["products"] = Config.Products["laptop"],
        ["showblip"] = false,
    },
    ["legionmarket"] = {
        ["label"] = "Legion Market",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(226.2, -908.77, 30.73),
            [2] = vector3(226.2, -908.77, 30.73)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
    },
    ["robsliquor6"] = {
        ["label"] = "Casino Bar",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(936.1185, 28.61719, 71.833)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
    },
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-1222.77, -907.19, 12.32)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-707.41, -912.83, 19.21),
            [2] = vector3(-707.32, -914.65, 19.21)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-1487.7, -378.53, 40.16)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-1820.33, 792.66, 138.1),
            [2] = vector3(-1821.55, 793.98, 138.1)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-2967.79, 391.64, 15.04)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-3038.71, 585.9, 7.9),
            [2] = vector3(-3041.04, 585.11, 7.9)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["legionshop"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(240.12234, -897.5831, 29.623193)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["police"] = {
        ["label"] = "Police Cafeteria",
        ["type"] = "police",
        ["coords"] = {
            [1] = vector3(460.32, -969.95, 35.8),
        },
        ["products"] = Config.Products["police"],
        ["showblip"] = false,
    },
    ["CUSTOMCAFE"] = {
        ["label"] = "Cafe Cafeteria",
        ["type"] = "CUSTOMCAFE",
        ["coords"] = {
            [1] = vector3(330.74395, -890.5238, 60.192935),
        },
        ["products"] = Config.Products["CUSTOMCAFE"],
        ["showblip"] = false,
    },
    ["darkcivthings"] = {
        ["label"] = "Dark Things",
        ["type"] = "darkcivthings",
        ["coords"] = {
            [1] = vector3(-570.3253, 232.99697, 74.890838),
        },
        ["products"] = Config.Products["darkcivthings"],
        ["showblip"] = false,
    },
    ["CUSTOMCAFEDRINKS"] = {
        ["label"] = "Cafe Cafeteria Drinks",
        ["type"] = "CUSTOMCAFE",
        ["coords"] = {
            [1] = vector3(331.42807, -881.7791, 60.194526),
        },
        ["products"] = Config.Products["CUSTOMCAFEDRINKS"],
        ["showblip"] = false,
    },
    ["casino1"] = {
        ["label"] = "Casino Shop",
        ["type"] = "casino1",
        ["coords"] = {
            [1] = vector3(1115.1046, -2311.546, 24.453968),
        },
        ["products"] = Config.Products["casino1"],
        ["showblip"] = false,
    },
    ["repairkitbennys"] = {
        ["label"] = "Bennys Repairkit",
        ["type"] = "repairkitbennys",
        ["coords"] = {
            [1] = vector3(-32.57725, -1056.449, 27.792751),
        },
        ["products"] = Config.Products["repairkitbennys"],
        ["showblip"] = false,
    },
    ["repairkitbennys2"] = {
        ["label"] = "Bennys Repairkit",
        ["type"] = "repairkitbennys2",
        ["coords"] = {
            [1] = vector3(-34.89126, -1052.849, 27.790214),
        },
        ["products"] = Config.Products["repairkitbennys2"],
        ["showblip"] = false,
    },
    ["casino2"] = {
        ["label"] = "Club77 Chips Shop",
        ["type"] = "casino2",
        ["coords"] = {
            [1] = vector3(249.45231, -3151.56, 3.3248801),
        },
        ["products"] = Config.Products["casino2"],
        ["showblip"] = false,
    },
    ["yellowjack"] = {
        ["label"] = "Yellow Jack Shop",
        ["type"] = "yellowjack",
        ["coords"] = {
            [1] = vector3(1988.1159, 3047.1145, 47.20927),
        },
        ["products"] = Config.Products["yellowjack"],
        ["showblip"] = false,
    },
    ["taco"] = {
        ["label"] = "Taco",
        ["type"] = "taco",
        ["coords"] = {
            [1] = vector3(375.18765, -319.1976, 46.955841),
        },
        ["products"] = Config.Products["taco"],
        ["showblip"] = false,
    },
    ["mechanictools"] = {
        ["label"] = "Mechanic Dark Tools",
        ["type"] = "mechanictools",
        ["coords"] = {
            [1] = vector3(157.39074, -2997.833, 7.0321307),
        },
        ["products"] = Config.Products["mechanictools"],
        ["showblip"] = false,
    },
    ["mechanictools2"] = {
        ["label"] = "Redline Dark Tools",
        ["type"] = "mechanictools2",
        ["coords"] = {
            [1] = vector3(477.70724, -569.4756, 28.500165),
        },
        ["products"] = Config.Products["mechanictools2"],
        ["showblip"] = false,
    },
    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-3241.47, 1001.14, 12.83),
            [2] = vector3(-3243.98, 1001.35, 12.83)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1728.66, 6414.16, 35.03),
            [2] = vector3(1729.72, 6416.27, 35.03)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1697.99, 4924.4, 42.06),
            [2] = vector3(1699.44, 4923.47, 42.06)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1961.48, 3739.96, 32.34),
            [2] = vector3(1960.22, 3742.12, 32.34)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1165.28, 2709.4, 38.15)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(547.79, 2671.79, 42.15),
            [2] = vector3(548.1, 2669.38, 42.15)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(2679.25, 3280.12, 55.24),
            [2] = vector3(2677.13, 281.38, 55.24)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(2557.94, 382.05, 108.62),
            [2] = vector3(2555.53, 382.18, 108.62)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(240.19612, -897.5624, 29.623239)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["digitalden"] = {
        ["label"] = "Digital Den",
        ["type"] = "digitalden",
        ["coords"] = {
            [1] = vector3(149.08, -234.68, 54.42),
        },
        ["products"] = Config.Products["digitalden"],
        ["showblip"] = false,
    },
    ["delvecchioliquor"] = {
        ["label"] = "Del Vecchio Liquor",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(-155.87, 6327.5, 31.58),
            [2] = vector3(-155.87, 6327.5, 31.58)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["donscountrystore"] = {
        ["label"] = "Don's Country Store",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(161.19, 6639.87, 31.7)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1163.7, -323.92, 69.2),
            [2] = vector3(1163.4, -322.24, 69.2)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(1135.66, -982.76, 46.41)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(373.55, 325.56, 103.56),
            [2] = vector3(374.29, 327.9, 103.56)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
    },
    ["247supermarket11"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = {
            [1] = vector3(324.67984, -583.8979, 43.270233)
        },
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
    },
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["type"] = "hardware",
        ["coords"] = {
            [1] = vector3(45.55, -1749.01, 29.6)
        },
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
    },
    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["type"] = "hardware",
        ["coords"] = {
            [1] = vector3(2747.8, 3472.86, 55.67)
        },
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
    },
    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["type"] = "hardware",
        ["coords"] = {
            [1] = vector3(-421.84, 6136.09, 31.78)
        },
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
    },   
    ["petstore"] = {
        ["label"] = "Pet Store",
        ["type"] = "petstore",
        ["coords"] = {
            [1] = vector3(-1366.578, 56.785236, 54.098445)
        },
        ["products"] = Config.Products["petstore"],
        ["showblip"] = false,
    },  
    ["beekeeping"] = {
        ["label"] = "Beekeeping Store",
        ["type"] = "beekeeping",
        ["coords"] = {
            [1] = vector3(1531.6072, 1728.0599, 109.92362)
        },
        ["products"] = Config.Products["beekeeping"],
        ["showblip"] = false,
    },  
    ["coffeeshop"] = {
        ["label"] = "Superfly",
        ["type"] = "coffeeshop",
        ["coords"] = {
            [1] = vector3(-1172.43, -1572.24, 4.66)
        },
        ["products"] = Config.Products["coffeeshop"],
        ["showblip"] = true,
    },
    ["ammunation1"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(-662.9967, -933.5181, 21.829208)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(810.8161, -2159.02, 29.618986)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(1691.6148, 3760.2719, 34.705326)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(-332.3212, 6084.2412, 31.454757)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(254.09423, -49.82761, 69.941032)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(22.383785, -1105.418, 29.796997)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(2567.9238, 292.58334, 108.73482)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(-1118.937, 2699.7373, 18.554119)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = false,
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(842.82, -1028.66, 28.19)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = {
            [1] = vector3(843.06469, -1035.347, 28.194833)
        },
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
    },
    ["seaword1"] = {
        ["label"] = "Sea Word",
        ["type"] = "sea",
        ["coords"] = {
            [1] = vector3(-1686.9, -1072.23, 13.15)
        },
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = false,
    },
    ["electricshop"] = {
        ["label"] = "Electric Shop",
        ["type"] = "electricshop",
        ["coords"] = {
            [1] = vector3(1134.18, -467.95, 66.49)
        },
        ["products"] = Config.Products["electricshop"],
        ["showblip"] = true,
    },
    ["pawnshop"] = {
        ["label"] = "Pawn Shop",
        ["type"] = "pawnshop",
        ["coords"] = {
            [1] = vector3(-329.3953, -93.15591, 47.047351)
        },
        ["products"] = Config.Products["pawnshop"],
        ["showblip"] = false,
    },
    -- ["blackmarketvpn"] = {
    --     ["label"] = "Black Market Vpn",
    --     ["type"] = "blackmarketvpn",
    --     ["coords"] = {
    --         [1] = vector3(261.23574, -1004.961, 61.635578)
    --     },
    --     ["products"] = Config.Products["blackmarketvpn"],
    --     ["showblip"] = false,
    -- },
    -- ["attch"] = {
    --     ["label"] = "Weapons Attachments",
    --     ["type"] = "attch",
    --     ["coords"] = {
    --         [1] = vector3(2340.2968, 3058.2839, 48.151893)
    --     },
    --     ["products"] = Config.Products["attch"],
    --     ["showblip"] = false,
    -- },
    ["pokemonstore"] = {
        ["label"] = "Pokemon Shop",
        ["coords"] = {
            [1] = vector3(-320.5304, -103.7714, 46.897592)
        },
        ["products"] = Config.Products["pokemon"],
        ["showblip"] = false,
        ["blipsprite"] = 52
    },
    -- ["leisureshop"] = {
    --     ["label"] = "Leisure Shop",
    --     ["type"] = "leisure",
    --     ["coords"] = {
    --         [1] = vector3(-1505.91, 1511.78, 115.29)
    --     },
    --     ["products"] = Config.Products["leisureshop"],
    --     ["showblip"] = true,
    -- },
}
