import { iClientInfo, iVehicleInfo } from "@/types/BasicTypes";
import { debugData } from "@/utils/debugData";

debugData([
  { action: "ui:setSettingsOpen", data: true },
  {
    action: "ui:setHudData",
    data: {
      client_info: {
        radio: { show: true, inChannel: true, channel: 6 },
        player_source: { show: true, source: 1 },
        time: { show: true, gameHours: 23, gameMinutes: 0 },
        server_info: { show: true, image: "index.png", name: "0Resmon", playerCount: 6, maxPlayers: 32 },
        cash: { show: true, amount: 1000 },
        bank: { show: true, amount: 1000 },
        extra_currency: { show: true, amount: 777 },
        job: { show: true, label: "LSPD", gradeLabel: "Officer" },
        weapon: { show: true, name: "Pistol II", ammo: { inClip: 8, inWeapon: 32 } },
      } as iClientInfo,
      vehicle_info: {
        entity: 1,
        speed: 100,
        rpm: 0.85,
        fuel: { level: 45, maxLevel: 100, type: "gasoline" },
        currentGear: 2,
        veh_class: 1,
      } as iVehicleInfo,
      bars: {
        armor: { value: 50, autoHide: 100, color: "#1d4ed8" },
        health: { value: 50, autoHide: 100, color: "#CF4E5B" },
        hunger: { value: 50, autoHide: 100, color: "#FFC400" },
        oxygen: { value: 0, autoHide: 99, color: "#00FFA3" },
        stamina: { value: 50, autoHide: 100, color: "#C4FF48" },
        stress: { value: 50, autoHide: 100, color: "#6b21a8" },
        thirst: { value: 50, autoHide: 100, color: "#00C2FF" },
        vehicle_engine: { value: 50, autoHide: 99, color: "#C4FF48" },
        voice: { value: 50, autoHide: 100, color: "#FFFFFF", isTalking: true, talkRange: 2 },
        vehicle_nitro: { value: 10, autoHide: 99, color: "#CF654E" },
      },
    },
  },
  {
    action: "ui:setupUI",
    data: {
      setLocale: {
        locale: "en",
        data: {
          auto_hide: "Auto Hide",
          map_type: "Map Type",
          desc_map_type: "You can change the shape of the map according to your preference.",
          time: "Time",
          cash: "Cash",
          bank: "Bank",
          current_job: "Current Job",
          weapon: "Weapon",
          music: "Music",
          seat: "Seat",
          user_id: "User ID",
          radio: "Radio",
          server_info: "Server Info",
          navigation_widget: "Navigation Widget",
          compass_only_vehicle: "Compass Only In Vehicle",
          compass: "Compass",
          minimap_only_vehicle: "Minimap Only In vehicle",
          circle: "Circle",
          zarg: "Zarg",
          classic: "Classic",
          hexagon: "Hexagon",
          "hexagon-w": "Hexagon",
          "grt-premium": "Grt",
          square: "Square",
          "zarg-m": "Zarg",
          "wave-c": "Wave",
          "wave-h": "Wave",
          universal: "Universal",
          none: "None",
          hunger: "Hunger",
          health: "Health",
          thirst: "Thirst",
          armor: "Armor",
          stamina: "Stamina",
          oxygen: "Oxygen",
          stress: "Stress",
          voice: "Voice",
          vehicle_engine: "Engine",
          res_style_seq: "Res Style Sequence",
          movie_bars: "Movive Bars",
          location: "Location",
          players: "Players",
          desc_autohide: "0 Hide | 100 Visible",
          vehicle_nitro: "Nitro",
          reset_all_positions: "Reset All Positions",
          hbk: "HBK",
          abs: "ABS",
          gear: "Gear",
          time_bomb: "Time-B",
          classic_old: "Classic",
          semi_circle: "Semi-C",
          grt_one: "Grt One",
          grt_two: "Grt Two",
          globe: "Globe",
          editor_mode: "Editor Mode",
          hud_v2: "Old-V",
          race_hud: "Old-R",
          bmg: "BMG",
          gmg: "GMG",
          bar_default_size: "Default Bar Size",
          money_type: "$",
          clear_cache: "Clear Cache",
          edit_mini_map: "Edit Mini Map",
          reset_mini_map: "Reset Mini Map",
          other_currency: "Black Money",
        },
      },
    },
  },
] as any);
