fx_version 'cerulean'
lua54 'yes'
game 'gta5'
name '0r-illegalpack'
author '0resmon & alikoc.dev'
version '1.1.3'
description 'Illegal Job Pack | alikoc.dev'

shared_scripts {
    '@ox_lib/init.lua',
    'config.lua',
    'shared/init.lua',
}

files {
    'locales/en.json',
    'modules/bridge/esx/client.lua',
    'modules/bridge/qb/client.lua',
    'modules/bridge/qbx/client.lua',
    'modules/digiscanner/client.lua',
    'modules/exports/client.lua',
    'modules/target/client.lua',
    'modules/utils/client.lua',
    'modules/weather/client.lua',
    'modules/bridge/init.lua',
    'escrow/jobs/bag_snatch/config.lua',
    'escrow/jobs/car_theft/config.lua',
    'escrow/jobs/chicken_kidnapping/config.lua',
    'escrow/jobs/chop_shop/config.lua',
    'escrow/jobs/cocaine_job/config.lua',
    'escrow/jobs/container_heli/config.lua',
    'escrow/jobs/corner_deal/config.lua',
    'escrow/jobs/counterfeit_money/config.lua',
    'escrow/jobs/diving/config.lua',
    'escrow/jobs/fraud/config.lua',
    'escrow/jobs/gun_smuggling/config.lua',
    'escrow/jobs/illegal_delivery/config.lua',
    'escrow/jobs/meth_job/config.lua',
    'escrow/jobs/money_laundering/config.lua',
    'escrow/jobs/moonshine/config.lua',
    'escrow/jobs/npc_boxing/config.lua',
    'escrow/jobs/plane_drug_delivery/config.lua',
    'escrow/jobs/weed_job/config.lua',
    'escrow/market/config.lua',
    'ui/build/index.html',
    'ui/build/assets/index-BA1jSRRv.js',
    'ui/build/assets/index-D-mUWqdQ.css',
    'ui/build/images/common/fraud_bg.png',
    'ui/build/images/common/f_credit_card.png',
    'ui/build/images/common/mask_01.png',
    'ui/build/images/common/profile_01.png',
    'ui/build/images/common/profile_02.png',
    'ui/build/images/common/profile_03.png',
    'ui/build/images/common/profile_04.png',
    'ui/build/images/common/profile_05.png',
    'ui/build/images/common/profile_06.png',
    'ui/build/images/common/profile_07.png',
    'ui/build/images/common/profile_08.png',
    'ui/build/images/common/union_01.png',
    'ui/build/images/common/union_02.png',
    'ui/build/images/common/union_invite_modal.png',
    'ui/build/images/common/union_job_info.png',
    'ui/build/images/common/union_market_item.png',
    'ui/build/images/common/union_progress.png',
    'ui/build/images/icons/diamond.svg',
    'ui/build/images/icons/info.svg',
    'ui/build/images/icons/lock.svg',
    'ui/build/images/icons/shop.svg',
    'ui/build/images/icons/star.svg',
    'ui/build/images/icons/thief.svg',
    'ui/build/images/icons/userinvite.svg',
    'ui/build/items/adrenaline.png',
    'ui/build/items/ammonia.png',
    'ui/build/items/anchor.png',
    'ui/build/items/atm_hack_device.png',
    'ui/build/items/atm_hack_phone.png',
    'ui/build/items/atm_hack_tablet.png',
    'ui/build/items/blank_card.png',
    'ui/build/items/blended_ingredients.png',
    'ui/build/items/breaked_meth.png',
    'ui/build/items/cooked_meth.png',
    'ui/build/items/copperwire.png',
    'ui/build/items/credit_card.png',
    'ui/build/items/crushed_ingredients.png',
    'ui/build/items/cutted_coke.png',
    'ui/build/items/cutted_money.png',
    'ui/build/items/fake_credit_card.png',
    'ui/build/items/illegal_tablet.png',
    'ui/build/items/lockpick.png',
    'ui/build/items/medkit.png',
    'ui/build/items/money_sheet.png',
    'ui/build/items/moonshine.png',
    'ui/build/items/moonshine_pack.png',
    'ui/build/items/moonshine_still.png',
    'ui/build/items/old_corn.png',
    'ui/build/items/old_fruit.png',
    'ui/build/items/packed_coke.png',
    'ui/build/items/packed_meth.png',
    'ui/build/items/packed_weed.png',
    'ui/build/items/painkiller.png',
    'ui/build/items/plant_spray.png',
    'ui/build/items/powdered_milk.png',
    'ui/build/items/rolled_weed.png',
    'ui/build/items/sacid.png',
    'ui/build/items/scrapmetal.png',
    'ui/build/items/stolen_bag.png',
    'ui/build/items/tap_water.png',
    'ui/build/items/uncutted_money.png',
    'ui/build/items/unpacked_coke.png',
    'ui/build/items/unpacked_weed.png',
    'ui/build/items/WEAPON_CROWBAR.png',
    'ui/build/items/WEAPON_DIGISCANNER.png',
    'ui/build/job_banners/bag_snatch.png',
    'ui/build/job_banners/car_theft.png',
    'ui/build/job_banners/chicken_kidnapping.png',
    'ui/build/job_banners/chop_shop.png',
    'ui/build/job_banners/cocaine.png',
    'ui/build/job_banners/container_heli.png',
    'ui/build/job_banners/corner_deal.png',
    'ui/build/job_banners/counterfeit_money.png',
    'ui/build/job_banners/diving.png',
    'ui/build/job_banners/fraud.png',
    'ui/build/job_banners/gun_smuggling.png',
    'ui/build/job_banners/illegal_delivery.png',
    'ui/build/job_banners/illegal_mining.png',
    'ui/build/job_banners/laundering.png',
    'ui/build/job_banners/meth_lab.png',
    'ui/build/job_banners/moonshine.png',
    'ui/build/job_banners/npc_boxing.png',
    'ui/build/job_banners/plane_drug_delivery.png',
    'ui/build/job_banners/weed_job.png',
    'stream/horoz_cage.ytyp',
}

client_scripts {
    'escrow/jobs/client_index.lua',
    'escrow/chat/client.lua',
    'escrow/jobs/bag_snatch/client.lua',
    'escrow/jobs/car_theft/client.lua',
    'escrow/jobs/chicken_kidnapping/client.lua',
    'escrow/jobs/chop_shop/client.lua',
    'escrow/jobs/cocaine_job/client.lua',
    'escrow/jobs/container_heli/client.lua',
    'escrow/jobs/corner_deal/client.lua',
    'escrow/jobs/counterfeit_money/client.lua',
    'escrow/jobs/diving/client.lua',
    'escrow/jobs/fraud/client.lua',
    'escrow/jobs/gun_smuggling/client.lua',
    'escrow/jobs/illegal_delivery/client.lua',
    'escrow/jobs/meth_job/client.lua',
    'escrow/jobs/money_laundering/client.lua',
    'escrow/jobs/moonshine/client.lua',
    'escrow/jobs/npc_boxing/client.lua',
    'escrow/jobs/plane_drug_delivery/client.lua',
    'escrow/jobs/weed_job/client.lua',
    'escrow/lobby/client.lua',
    'escrow/market/client.lua',
    'escrow/profile/client.lua',
    'client.lua',
    'shared/client_debug.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'escrow/jobs/server_index.lua',
    'escrow/chat/server.lua',
    'escrow/jobs/bag_snatch/server.lua',
    'escrow/jobs/car_theft/server.lua',
    'escrow/jobs/chicken_kidnapping/server.lua',
    'escrow/jobs/chop_shop/server.lua',
    'escrow/jobs/cocaine_job/server.lua',
    'escrow/jobs/container_heli/server.lua',
    'escrow/jobs/corner_deal/server.lua',
    'escrow/jobs/counterfeit_money/server.lua',
    'escrow/jobs/diving/server.lua',
    'escrow/jobs/fraud/server.lua',
    'escrow/jobs/gun_smuggling/server.lua',
    'escrow/jobs/illegal_delivery/server.lua',
    'escrow/jobs/meth_job/server.lua',
    'escrow/jobs/money_laundering/server.lua',
    'escrow/jobs/moonshine/server.lua',
    'escrow/jobs/npc_boxing/server.lua',
    'escrow/jobs/plane_drug_delivery/server.lua',
    'escrow/jobs/weed_job/server.lua',
    'escrow/lobby/server.lua',
    'escrow/market/server.lua',
    'escrow/profile/server.lua',
    'server.lua',
}

ui_page 'ui/build/index.html'

data_file 'DLC_ITYP_REQUEST' 'stream/horoz_cage.ytyp'

dependencies { 'ox_lib', 'oxmysql', '0r_lib' }

escrow_ignore {
    'config.lua',
    'shared/client_debug.lua',
    'shared/init.lua',
    'shared/types/__job.lua',
    'shared/types/__lobby.lua',
    'shared/types/__market.lua',
    'modules/bridge/init.lua',
    'modules/bridge/esx/client.lua',
    'modules/bridge/esx/server.lua',
    'modules/bridge/qb/client.lua',
    'modules/bridge/qb/server.lua',
    'modules/bridge/qbx/client.lua',
    'modules/bridge/qbx/server.lua',
    'modules/digiscanner/client.lua',
    'modules/exports/client.lua',
    'modules/exports/server.lua',
    'modules/inventory/server.lua',
    'modules/lockmanager/server.lua',
    'modules/mysql/server.lua',
    'modules/target/client.lua',
    'modules/utils/client.lua',
    'modules/utils/server.lua',
    'modules/weather/client.lua',
    'escrow/jobs/bag_snatch/config.lua',
    'escrow/jobs/car_theft/config.lua',
    'escrow/jobs/chicken_kidnapping/config.lua',
    'escrow/jobs/chop_shop/config.lua',
    'escrow/jobs/cocaine_job/config.lua',
    'escrow/jobs/container_heli/config.lua',
    'escrow/jobs/corner_deal/config.lua',
    'escrow/jobs/counterfeit_money/config.lua',
    'escrow/jobs/diving/config.lua',
    'escrow/jobs/fraud/config.lua',
    'escrow/jobs/gun_smuggling/config.lua',
    'escrow/jobs/illegal_delivery/config.lua',
    'escrow/jobs/meth_job/config.lua',
    'escrow/jobs/money_laundering/config.lua',
    'escrow/jobs/moonshine/config.lua',
    'escrow/jobs/npc_boxing/config.lua',
    'escrow/jobs/plane_drug_delivery/config.lua',
    'escrow/jobs/weed_job/config.lua',
    'escrow/market/config.lua',
}

dependency '/assetpacks'

